import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { runInNewContext } from 'node:vm';
const ts = createRequire(import.meta.url)('typescript');
const source = readFileSync(new URL('../src/performer-room-selection.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS } }).outputText;
const exports = {};
runInNewContext(compiled, { exports });
const { readPerformerRoomSelection: read, savePerformerRoomSelection: save } = exports;
const idA = JSON.stringify(['account-a', 'performer-a']);
const idB = JSON.stringify(['account-b', 'performer-b']);
const roomA = '11111111-1111-4111-8111-111111111111';
const roomB = '22222222-2222-4222-8222-222222222222';
const values = new Map();
const storage = { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
let passed = 0;
function test(name, action) { action(); passed += 1; console.log(`ROOM_SELECTION_PASS ${name}`); }
test('no confirmed identity cannot read or write a selection', () => { save(null, roomA, storage); assert.equal(values.size, 0); assert.equal(read(null, storage), null); });
test('remembered room survives a new read without storing private state', () => { save(idA, roomA, storage); assert.equal(read(idA, storage), roomA); assert.deepEqual([...values.values()], [roomA]); });
test('a second account does not inherit the first account room', () => { assert.equal(read(idB, storage), null); save(idB, roomB, storage); assert.equal(read(idA, storage), roomA); assert.equal(read(idB, storage), roomB); });
test('clearing an account leaves another account selection untouched', () => { save(idA, null, storage); assert.equal(read(idA, storage), null); assert.equal(read(idB, storage), roomB); });
test('reselection updates only the intended account', () => { save(idA, roomA, storage); save(idA, roomB, storage); assert.equal(read(idA, storage), roomB); assert.equal(read(idB, storage), roomB); });
test('invalid room ids clear stale selections rather than becoming routes', () => { for (const bad of ['not-a-room', '../other', '', 'https://example.invalid', `${roomA}?other=1`]) { save(idA, bad, storage); assert.equal(read(idA, storage), null); } });
test('malformed stored values are rejected and removed', () => { save(idA, roomA, storage); const key = [...values.keys()].find(key => key.endsWith(idA)); storage.setItem(key, '{"session":"private"}'); assert.equal(read(idA, storage), null); assert.equal(values.has(key), false); });
test('unavailable storage does not break room actions', () => { assert.equal(read(idA, null), null); assert.doesNotThrow(() => save(idA, roomA, null)); });
test('blocked or full storage never throws into the interface', () => { const blocked = { getItem() { throw new Error('blocked'); }, setItem() { throw new Error('full'); }, removeItem() { throw new Error('blocked'); } }; assert.equal(read(idA, blocked), null); assert.doesNotThrow(() => save(idA, roomA, blocked)); assert.doesNotThrow(() => save(idA, null, blocked)); });
test('server rendering has no browser storage dependency', () => { assert.equal(read(idA), null); assert.doesNotThrow(() => save(idA, roomA)); });
console.log(`ROOM_SELECTION_SUMMARY ${JSON.stringify({ passed, failed: 0 })}`);
